const productos =[
    /* TINTOS */
    /* -----------------------MALBEC -----------------------*/
    {
        id: "1",
        nombre: 'Killka',
        variedad: 'Tinto',
        varietal: 'Malbec', 
        bodega: 'Salentein Wines',
        precio: 2400,
        imagen: "./img/MALBEC/Killka_Malbec.png",
    },
    {
        id: "2",
        nombre: 'Benjamin',
        variedad: 'Tinto',
        varietal: 'Malbec', 
        bodega: 'Nieto Senetiner',
        precio: 2170,
        imagen:"./img/MALBEC/Benjamin_Malbec_2022.png",
    },
    {
        id: "3",
        nombre: 'Portillo',
        variedad: 'Tinto',
        varietal: 'Malbec', 
        bodega: 'Salentein Wines',
        precio: 2500,
        imagen:"./img/MALBEC/Portillo_Mlabec.png",
    },
    {
        id: "4",
        nombre: 'Don Nicanor',
        variedad: 'Tinto',
        varietal: 'Malbec', 
        bodega: 'Nieto Senetiner',
        precio: 5540,
        imagen:"./img/MALBEC/don nicanor malbec.png",
    },
    {
        id: "5",
        nombre: 'Fran',
        variedad: 'Tinto',
        varietal: 'Malbec', 
        bodega: 'Nieto Senetiner',
        precio: 5000,
        imagen:"./img/MALBEC/Fran_Malbec_2022.png",
    },
    {
        id: "6",
        nombre: 'Salentein Reserva',
        variedad: 'Tinto',
        varietal: 'Malbec', 
        bodega: 'Salentein Wines',
        precio: 5000,
        imagen:"./img/MALBEC/SALENTEIN Reserva_Malbec.png",
    },
    {
        id: "7",
        nombre: 'Emilia',
        variedad: 'Tinto',
        varietal: 'Malbec', 
        bodega: 'Nieto Senetiner',
        precio: 5000,
        imagen:"./img/MALBEC/Emilia_Malbec_2022.png",
    },

        /* -----------------------CABERNET -----------------------*/
    {
        id: "10",
        nombre: 'Killka',
        variedad: 'Tinto',
        varietal: 'Cabernet Sauvignon', 
        bodega: 'Salentein Wines',
        precio: 2400,
        imagen:"./img/CABERNET/killka cs.png",
    },  
    {
        id: "11",
        nombre: 'Portillo',
        variedad: 'Tinto',
        varietal: 'Cabernet Sauvignon', 
        bodega: 'Salentein Wines',
        precio: 2500,
        imagen:"./img/CABERNET/portillo cs.png",
    },
    {
        id: "12",
        nombre: 'Benjamin',
        variedad: 'Tinto',
        varietal: 'Cabernet Sauvignon', 
        bodega: 'Nieto Senetiner',
        precio: 2170,
        imagen:"./img/CABERNET/benjamin cs.png",
    },
    {
        id: 13,
        nombre: 'Don Nicanor',
        variedad: 'Tinto',
        varietal: 'Cabernet Sauvignon', 
        bodega: 'Nieto Senetiner',
        precio: 5540,
        imagen:"./img/CABERNET/don nicanor cs.png",
    },
    {
        id: "14",
        nombre: 'Salentein Reserva',
        variedad: 'Tinto',
        varietal: 'Cabernet Sauvignon', 
        bodega: 'Salentein Wines',
        precio: 5000,
        imagen:"./img/CABERNET/salentein reservs cs.png",
    },
    {
        id: "15",
        nombre: 'Emilia',
        variedad: 'Tinto',
        varietal: 'Cabernet Sauvignon', 
        bodega: 'Nieto Senetiner',
        precio: 5000,
        imagen:"./img/CABERNET/emilia cs.png",
    },

        /* -----------------------MERLOT -----------------------*/
    {
        id: "17",
        nombre: 'Salentein Reserva',
        variedad: 'Tinto',
        varietal: 'Merlot', 
        bodega: 'Salentein Wines',
        precio: 5000,
        imagen:"./img/MERLOT/salenteint merlot.png",
    },
    {
        id: "18",
        nombre: 'Portillo',
        variedad: 'Tinto',
        varietal: 'Merlot', 
        bodega: 'Salentein Wines',
        precio: 2500,
        imagen:"./img/MERLOT/Portillo_merlot.png",
    },
    {
        id: "21",
        nombre: 'Benjamin',
        variedad: 'Tinto',
        varietal: 'Merlot', 
        bodega: 'Nieto Senetiner',
        precio: 2170,
        imagen:"./img/MERLOT/benjamin merlot.png",
    },
    
    /* BLANCOS */

        /* -----------------------CHARDONNAY -----------------------*/
    {
        id: "22",
        nombre: 'Benjamin',
        variedad: 'Blanco',
        varietal: 'Chardonnay', 
        bodega: 'Nieto Senetiner',
        precio: 2170,
        imagen:"./img/CHARDONNAY/benjamin chardonnay.png",
    },
    {
        id: "23",
        nombre: 'Don Nicanor',
        variedad: 'Blanco',
        varietal: 'Chardonnay', 
        bodega: 'Nieto Senetiner',
        precio: 5540,
        imagen:"./img/CHARDONNAY/don nicanor chardonnay.png",
    },
    {
        id: "24",
        nombre: 'Emilia',
        variedad: 'Blanco',
        varietal: 'Chardonnay', 
        bodega: 'Salentein Wines',
        precio: 5000,
        imagen:"./img/CHARDONNAY/emilia chardonnay.png",
    },
    {
        id: "26",
        nombre: 'Fran',
        variedad: 'Blanco',
        varietal: 'Chardonnay', 
        bodega: 'Nieto Senetiner',
        precio: 5000,
        imagen:"./img/CHARDONNAY/fran chardonnay.png",
    },
    {
        id: "27",
        nombre: 'Portillo',
        variedad: 'Blanco',
        varietal: 'Chardonnay', 
        bodega: 'Salentein Wines',
        precio: 2500,
        imagen:"./img/CHARDONNAY/portilla chardonnay.png",
    },
    {
        id: "28",
        nombre: 'Killka',
        variedad: 'Blanco',
        varietal: 'Chardonnay', 
        bodega: 'Salentein Wines',
        precio: 2400,
        imagen:"./img/CHARDONNAY/killka chardonnay.png",
    },
    {
        id: "29",
        nombre: 'Salentein Reserva',
        variedad: 'Blanco',
        varietal: 'Chardonnay', 
        bodega: 'Salentein Wines',
        precio: 5000,
        imagen:"./img/CHARDONNAY/salentein chardonnay.png",
    },

        /* -----------------------SAUVIGNON BLANC -----------------------*/
    {
        id: "32",
        nombre: 'Benjamin',
        variedad: 'Blanco',
        varietal: 'Sauvignon Blanc', 
        bodega: 'Nieto Senetiner',
        precio: 2170,
        imagen:"./img/SAUVIGNON BLANC/benjamin sb.png",
    },
    {
        id: "33",
        nombre: 'Emilia',
        variedad: 'Blanco',
        varietal: 'Sauvignon Blanc', 
        bodega: 'Nieto Senetiner',
        precio: 5000,
        imagen:"./img/SAUVIGNON BLANC/emilia sb.png",
    },
    {
        id: "34",
        nombre: 'Killka',
        variedad: 'Blanco',
        varietal: 'Sauvignon Blanc', 
        bodega: 'Salentein Wines',
        precio: 2400,
        imagen:"./img/SAUVIGNON BLANC/killka sb.png",
    },
    {
        id: "35",
        nombre: 'Portillo',
        variedad: 'Blanco',
        varietal: 'Sauvignon Blanc', 
        bodega: 'Salentein Wines',
        precio: 2500,
        imagen:"./img/SAUVIGNON BLANC/portillo sb.png",
    },
    {
        id: "37",
        nombre: 'Salentein Reserva',
        variedad: 'Blanco',
        varietal: 'Sauvignon Blanc', 
        bodega: 'Salentein Wines',
        precio: 5000,
        imagen:"./img/SAUVIGNON BLANC/salentein sb.png",
    },

        /* -----------------------ROSE -----------------------*/
    {
        id: "39",
        nombre: 'Benjamin',
        variedad: 'Rosado',
        varietal: 'Dulce', 
        bodega: 'Nieto Senetiner',
        precio: 2170,
        imagen:"./img/ROSE/benjamin rose.png",
    },
    {
        id: "40",
        nombre: 'Emilia',
        variedad: 'Rosado',
        varietal: 'Dulce', 
        bodega: 'Nieto Senetiner',
        precio: 5000,
        imagen:"./img/ROSE/emilia rose.png",
    },
    {
        id: "41",
        nombre: 'Portillo',
        variedad: 'Rosado',
        varietal: 'Rosé de Malbec', 
        bodega: 'Salentein Wines',
        precio: 2500,
        imagen:"./img/ROSE/portillo rose.png",
    },
    {
        id: "43",
        nombre: 'Salentein Reserva',
        variedad: 'Rosado',
        varietal: 'Rosé de Malbec', 
        bodega: 'Salentein Wines',
        precio: 5000,
        imagen:"./img/ROSE/SALENTEIN RESERVA ROSE.png",
    },
]

